version: 2
jobs:
  build:
    docker:
      - image: circleci/node:carbon
    steps:
      - checkout
      - run: sudo npm install gulp --global
      - restore_cache:
          key: yarn-{{ checksum "yarn.lock" }}
      - run: yarn
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths: [node_modules]
      - run: bash .circleci/build.sh
      - store_artifacts:
          path: packages
          prefix: packages
