version: 2
jobs:
  build:
    working_directory: ~/awesome-stars
    docker:
      - image: circleci/node:6.10.3
    steps:
      - checkout
      - run: sudo npm install gulp --global
      - restore_cache:
          key: yarn-{{ checksum "yarn.lock" }}
      - run: yarn
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: build
          command: |
            if [ "${CIRCLE_BRANCH}" == "develop" ] || [ "${CIRCLE_BRANCH}" == "master" ]; then
              gulp build --production --vendor=chrome
              gulp pack --vendor=chrome
            fi
      - store_artifacts:
          path: packages
          prefix: packages
